name: qr_staff
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core App Packages
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

  # QR & Scanner Features
  qr_flutter: ^4.0.0
  mobile_scanner: ^3.2.0

  # Charts & Sharing
  fl_chart: ^0.35.0
  share_plus: ^7.0.0
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
